### ISSUE TITLE
Forgot password screen

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-login-forms#3]
Up to date DSM link: https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/section/components/5b9ef26205bd76001ba35b4d

Utilises existing forgot password form.

**Comment by brynwhyman** [comment]
The existing forgot password form has validation expecting a '@' for an email address, is the intention that we now accept a username (and the extra functionality required to build that)? 
Or do we change the label to just prompt for an email address?
@clarkepaul 

Current wireframe: https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321188625

**Comment by clarkepaul** [comment]
@brynwhyman its a bit stupid reason but the initial accounts don't actually need an email address "Admin" can be used instead of an email address, so its still a hangover from that experience. No one else has a username. No extra functionality needed to accept a username but lets leave this as is for now.
