### ISSUE TITLE
Add the ability to disable this module

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-login-forms#56]
This module is a requirement of the MFA module, but may not always be desired, particularly in existing sites, so we should build config to turn it off.

This is particularly relevant to https://github.com/silverstripe/cwp/issues/258 where for those who want to opt-out, we're likely to reference YAML config available to by-pass MFA functionality, but the site would still include the login-forms functionality.

**Comment by ScopeyNZ** [comment]
`composer remove silverstripe/login-forms`?

**Comment by brynwhyman** [comment]
Sorry @ScopeyNZ, I've added a little more context to the issue

**Comment by ScopeyNZ** [comment]
If it's a component of cwp-installer, they can still remove it with `composer remove`, otherwise you can document removing it by using `composer require-recipe` to modify recipe requirements more speicifically.

I guess it just seems weird to me to install a bunch of code, and then use config to make that code completely inert - that goes for MFA too.

**Comment by brynwhyman** [comment]
I'm closing this. The priority to add the MFA bundle to the base CWP recipe has been dropped. The bundle has been added to the cwp-installer but developers have the option to composer remove the login-forms module from their project if not required.
