### ISSUE TITLE
Bump status to commercially supported module

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-login-forms#7]
Once feature work is finished on this repository and signed off, we should add this to the supported modules list.

- [x] Add to https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list site
- [x] Add to [supported-modules](https://github.com/silverstripe/supported-modules) repo

**Comment by robbieaverill** [comment]
I've done this, and added MFA, TOTP, WebAuthn, Security Extensions, and CKAN Registry. I've also added them to addons.silverstripe.org as supported (a checkbox in the CMS).

Note that we need to go through the addons site and mark everything as supported again, since the DB was wiped in May it's all gone.
